### DISCUSSION TITLE
Help regarding usage of IMGPROXY_GCS_ENDPOINT

### DISCUSSION THREAD

**Discussion by erwanriou** [imgproxy/imgproxy#1306] [Q&A] [answered]
i did a quick kubernetes config for `imgproxy` that work when i don't use the `IMGPROXY_GCS_ENDPOINT`

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageproxy-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageproxy
  template:
    metadata:
      labels:
        app: imageproxy
    spec:
      containers:
        - name: imageproxy
          image: darthsim/imgproxy:latest
          ports:
            - containerPort: 8080
          env:
            # DEFAULT CONFIGS
            - name: IMGPROXY_MAX_SRC_FILE_SIZE
              value: "0"
            - name: IMGPROXY_MAX_SRC_RESOLUTION
              value: "50"
            - name: IMGPROXY_DOWNLOAD_TIMEOUT
              value: "10"
            - name: IMGPROXY_TTL
              value: "31536000"
            - name: IMGPROXY_ENABLE_WEBP_DETECTION
              value: "true"
            - name: IMGPROXY_ENFORCE_WEBP
              value: "true"
            - name: IMGPROXY_SANITIZE_SVG
              value: "true"
            - name: IMGPROXY_ALLOWED_SOURCES
              value: "gs://my-private-bucket/*"
            # LOCAL CONFIG
            - name: IMGPROXY_IGNORE_SSL_VERIFICATION
              value: "true"
            # GCS CONFIGS
            - name: IMGPROXY_USE_GCS
              value: "true"
            - name: IMGPROXY_GCS_KEY
              valueFrom:
                secretKeyRef:
                  name: gcs-viewer-json
                  key: GCS_VIEWER_JSON
```

then if i try access a url like `https://assets.myproxyimage.dev/insecure/rs:fit:150:150:0:0/plain/gs://my-private-bucket/images/avatars/avatar3.jpg`

then it work fine

But when i setup for instance 

```txt
- name: IMGPROXY_GCS_ENDPOINT
  value: "gs://my-private-bucket"
```

i also tryed without the `gs://`, with a `/` at the end and a bunch of other thing

I just can't make it work like i would like for example `https://assets.myproxyimage.dev/insecure/rs:fit:150:150:0:0/plain/images/avatars/avatar3.jpg`

**So my question here is how this parameter work. I couldn't find any example about it.**
