### ISSUE TITLE
Feature request:  animated AVIF

### ISSUE THREAD

**Issue by routehero** [imgproxy/imgproxy#1226]
Animated WEBP is awesome!  

It would also be awesome to have animated AVIF!

In specific, the automatic conversion of animated GIF to webp or avif.

**Comment by DarthSim** [comment]
Hey @routehero!

It doesn't look like browsers have proper support for animated AVIFs nowadays. The only browser that properly plays AVIF animations is Safari. Chrome and Firefox seem to treat them like videos (which they honestly are) and play only a single loop.

**Comment by dbackeus** [comment]
As of todays versions, both Chrome and Safari appear to be looping animated AVIF correctly, checked via the example on this site: https://codecalamity.com/animated-avif-is-finally-coming-to-firefox/

(note that it's no longer necessary to explicitly enable the animation support in Firefox as stated in the article any longer)

**Comment by DarthSim** [comment]
That's interesting. The samples from https://colinbendell.github.io/webperf/animated-gif-decode/avif.html are still played just once in Firefox and Chrome.

**Comment by dbackeus** [comment]
I believe it might be down to parameters used when encoding the image. Not my area of expertise but it's what I gather from eg. https://github.com/AOMediaCodec/libavif/pull/1204

**Comment by igor-alexandrov** [comment]
@DarthSim I tried processing the first image from the samples page: https://colinbendell.github.io/webperf/animated-gif-decode/avif.html.

Without the `IMGPROXY_ENABLE_VIDEO_THUMBNAILS` setting I got

```
time="2026-05-12 19:40:11" level="WARNING" msg="Completed in 5.7995ms /unsafe/w:1600/plain/s3://safariportal-media-development/store/asset/2360771/file/063eaba88e233a5c072555a9a5209eb7.avif@jpg" request_id="O4iiaKJ-op50COs0VM1QR" method="GET" status=422 client_ip="172.21.0.1" error="can't download source image: failed to detect image type: failed to detect image type: The requested file is a video
```

With `IMGPROXY_ENABLE_VIDEO_THUMBNAILS: "true"` I got

```
time="2026-05-12 20:14:56" level="WARNING" msg="Completed in 22.151625ms /unsafe/w:1600/plain/s3://safariportal-media-development/store/asset/2360771/file/063eaba88e233a5c072555a9a5209eb7.avif@jpg" request_id="YOTU2f4dFLgJYQz9C28Dg" method="GET" status=422 client_ip="172.21.0.1" error="Can't make thumbnail for source video: Can't decode frame: Function not implemented"
```

The idea was to convert the first frame of the AVIF to JPG.

**Comment by DarthSim** [comment]
@igor-alexandrov I've tried this with v4, and imgproxy successfully generates static thumbnails for all the samples from that page (IMGPROXY_ENABLE_VIDEO_THUMBNAILS is enabled).

**Comment by igor-alexandrov** [comment]
@DarthSim I am on 4.0.0 and getting the error I pasted above.

**Comment by DarthSim** [comment]
@igor-alexandrov Could you share your config? I can't reproduce the issue with mine

**Comment by igor-alexandrov** [comment]
Of course.

```
imgproxy:
    image: <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/imgproxy:v4.0.0-ml
    environment:
      IMGPROXY_KEY: ""
      IMGPROXY_SALT: ""
      IMGPROXY_USE_S3: "true"
      IMGPROXY_S3_ENDPOINT: http://essie3:9000
      IMGPROXY_S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: fake_key
      AWS_SECRET_ACCESS_KEY: fake_secret
      IMGPROXY_ALLOW_ORIGIN: "*"
      IMGPROXY_LICENSE_KEY: ""
      IMGPROXY_SKIP_PROCESSING_FORMATS: "pdf"
      IMGPROXY_MAX_SRC_RESOLUTION: 75
      IMGPROXY_ENABLE_VIDEO_THUMBNAILS: "true"
    ports:
      - "8080:8080"
    depends_on:
      - essie3
```
