### ISSUE TITLE
Is it possible to cache the converted images on MinIO (S3)?

### ISSUE THREAD

**Issue by SuperNG6** [imgproxy/imgproxy#1322]
Thank you to all the developers for their hard work; this is a great piece of software. I would like to ask a question:  
Does imgproxy support caching transformed images to MinIO (S3)?  
就像这样. 
```yaml
  imgproxy:
    image: darthsim/imgproxy:latest
    environment:
      - IMGPROXY_USE_S3_CACHE=true
      - IMGPROXY_S3_CACHE_ENDPOINT=http://minio:9000
      - IMGPROXY_S3_CACHE_BUCKET=imgproxy-cache
```
