### ISSUE TITLE
S3 source - "Source image is unreachable" from 3.25.0

### ISSUE THREAD

**Issue by teddymelon** [imgproxy/imgproxy#1399]
Hello!

I am now using imgproxy (helmchart) as a part of service without signature and with source from AWS s3. The request url is like below:

https://imgproxy.domain.com/insecure/plain/s3://bucket_name/object_name

However, the request url doesn't work, and respond "Source image is unreachable".

helmchart ENV Variables：
```
image:
  repo: darthsim/imgproxy
  tag: v3.25.0
  pullPolicy: IfNotPresent

aws:
    # ENV['IMGPROXY_USE_S3']
    # when `true`, enables image fetching from Amazon S3 buckets.
    enabled: true

    # AWS account id (required for authentication using IAM Role)
    accountId: "xxxx"

    # ENV['AWS_ACCESS_KEY_ID']
    # AWS key
    accessKeyId: "xxxx"

    # ENV['AWS_SECRET_ACCESS_KEY']
    # AWS secret
    secretAccessKey: "xxxx"

    # ENV['IMGPROXY_S3_ASSUME_ROLE_ARN']
    # (3.17+) The AWS IAM Role to Assume
    iamRoleName: ""

    # ENV['IMGPROXY_S3_REGION']
    # AWS region
    s3Region: "us-west-2"

    # ENV['IMGPROXY_S3_ENDPOINT']
    # custom S3 endpoint to being used by imgproxy.
    s3Endpoint: ""

```

Error log：
```
error="Can't download source image: Unknown scheme: s3"
```

Does anyone have any idea about this?

Really appreciate that 🙇
