### ISSUE TITLE
IMGPROXY_ONLY_PRESETS allows non preset values

### ISSUE THREAD

**Issue by rhyst** [imgproxy/imgproxy#168]
I have a compose file for imgproxy that looks like:

```
version: '3'
services:
  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: imgproxy
    restart: always
    volumes:
     - /var/www/images:/images
    environment:
     - IMGPROXY_ALLOW_ORIGIN=*.my.site
     - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/images
     - IMGPROXY_MAX_SRC_RESOLUTION=25
     - IMGPROXY_PRESETS="default=width:0,sm=resizing_type:fit/width:200/height:200/gravity:sm/enlarge:0,md=resizing_type:fit/width:800/height:800/gravity:sm/enlarge:0,lg=resizing_type:fit/width:2000/height:2000/$
     - IMGPROXY_ONLY_PRESETS=true
```
Visiting `https://images.my.site/insecure/preset:sm/plain/http://url/image.jpg` will correctly show an image formatted to the preset values. However I can visit `https://images.my.site/insecure/fit/800/800/sm/0/plain/http://url/image.jpg` and it will also format the image according to those options. I would expect it to return an error, saying that only presets are allowed.
