### ISSUE TITLE
Source image is unreachable.

### ISSUE THREAD

**Issue by naughtydevelopment** [imgproxy/imgproxy#196]
I want to use minio and imgproxy together. My docker-compose like below. There is a image called `filan.jpg` in `falan` bucket. When I want to use that image with this url: `http://localhost:8082/resize/fit/100/100/no/0/plain/s3://falan/filan.jpg` I got `Source image is unreachable.` error. 

 I tried `IMGPROXY_S3_ENDPOINT` env variable various ways like `http://localhost:8081/minio` or `http://localhost:8081/` or `http://localhost:8081` but still dosen't work. Can anybody help me? 

Also my minio work localy. Don't integrated with `S3`.

```
version: '3.1'
services:
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: mystorage
      MINIO_SECRET_KEY: mystorage
    ports:
      - "8081:9000"
    volumes:
      - "./minio/storage:/data"
    command: server /data
  imgproxy:
    image: darthsim/imgproxy
    restart: always
    environment:
      IMGPROXY_USE_S3: 'true'
      AWS_ACCESS_KEY_ID: mystorage
      AWS_SECRET_ACCESS_KEY: mystorage
      IMGPROXY_S3_ENDPOINT: http://localhost:8081/minio
    ports:
      - "8082:8080"
```

imgproxy container env:

```
IMGPROXY_S3_ENDPOINT=http://localhost:8081/minio
HOSTNAME=36a201c20904
MALLOC_ARENA_MAX=4
VIPS_WARNING=0
PWD=/
IMGPROXY_USE_S3=true
HOME=/root
AWS_SECRET_ACCESS_KEY=mystorage
TERM=xterm
SHLVL=1
AWS_ACCESS_KEY_ID=mystorage
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

```

**Comment by DarthSim** [comment]
Hi,

We use minio for the dev needs on my current project, it works fine with imgproxy. That's how we launch them:

```
MINIO_ACCESS_KEY=access \
MINIO_SECRET_KEY=miniosecret \
MINIO_REGION=us-east-1 \
minio server --quiet --address localhost:9000 ./tmp/minio
```

```
IMGPROXY_USE_S3=true \ 
IMGPROXY_S3_ENDPOINT="http://localhost:9000" \
AWS_ACCESS_KEY_ID=access \
AWS_SECRET_ACCESS_KEY=miniosecret \
AWS_REGION=us-east-1 \
imgproxy
```

You probably forgot to specify a region. imgproxy logs should give you more info.

**Comment by naughtydevelopment** [comment]
Hi,

Thank you for your response. Before the REGION setting browser just download the image from minio with minio generated sharing URL. When I set the REGION and use the generated sharing URL after that my images was showable on the browser:
![Screen Shot 2019-08-21 at 21 57 48](https://user-images.githubusercontent.com/17801994/63460793-df5f1b00-c45f-11e9-8258-550a21c23b1a.png)

Thank you for this fix. But imgproxy still doesn't work. I think my request URL wrong. These are my imgproxy container logs. I tried various approach like below: 

This is without minio credential queries:

```
2019/08/21 18:58:29 [6_UMyS77omfkv0iBMXtdhe] GET: /resize/fit/100/100/no/0/plain/s3://falan/filan.jpg
2019/08/21 18:58:29 [6_UMyS77omfkv0iBMXtdhe] | 404 | Get s3://falan/filan.jpg: RequestError: send request failed
caused by: Get http://localhost:8081/falan/filan.jpg: dial tcp 127.0.0.1:8081: connect: connection refused
```

This; without the "http://localhost:8081" prefix and with other minio credential queries(this url generated from minio ui):
```
2019/08/21 18:55:38 [jx2qaBxwhbJXJsikwGsE4N] GET: /resize/fit/100/100/no/0/plain/s3://falan/filan.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=samimiyetsiz%2F20190821%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190821T185012Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=ceef23686e9849741af7bb1c5e20e1cd9c2f603cd84fcc3e876f8e2f46712574
2019/08/21 18:55:39 [jx2qaBxwhbJXJsikwGsE4N] | 404 | Get s3://falan/filan.jpg: RequestError: send request failed
caused by: Get http://localhost:8081/falan/filan.jpg: dial tcp 127.0.0.1:8081: connect: connection refused
```
I know imgproxy should make the credential things but I gave a chance any way. And I saw imgproxy doesn't give interest any thing after image extension.

Why my imgproxy can't download images from my minio. I still don't get it. What is the cause?

**Comment by naughtydevelopment** [comment]
Hi,

Shame on me. I read logs but I don't give any attention. I use host machine URLs in `docker-compose.yml` because of that imgproxy couldn't reach minio images. 

This is my last `docker-compose.yml`. And also I added some comment for others. In this example I use local filesystem and minio same time but you can choose any of them. 

```
version: '3.1'
services:
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: mystorage
      MINIO_SECRET_KEY: mystorage
      MINIO_REGION: us-east-1
    ports:
      - "8081:9000"
    volumes:
      - "./minio/storage:/data"
    command: server /data
  imgproxy:
    image: darthsim/imgproxy
    restart: always
    environment:
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /opt # you can link to minio volume to imgproxy and use as a local filesystem.
      IMGPROXY_USE_S3: 'true'
      IMGPROXY_S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: mystorage
      AWS_SECRET_ACCESS_KEY: mystorage
      AWS_REGION: us-east-1
    ports:
      - "8082:8080"
    links:
      - minio # it doesn't matter actually by default all containers can reach each other with their service name.
    volumes:
      - "./minio/storage:/opt" # link to minio volume to imgproxy's /opt folder for local filesystem.

```
