### ISSUE TITLE
Consider leaving curl or wget in the final stage of the docker image

### ISSUE THREAD

**Issue by douglasmiranda** [imgproxy/imgproxy#323]
It would be useful for `HEALTHCHECKS`.

When deploying using Docker we can use something like this:

```yaml
services:
  thumbnailer:
    image: darthsim/imgproxy:v2.8.2
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --spider http://localhost:8080/health || exit 1"
```
