### ISSUE TITLE
GCS enabled however error of "Unknown processing option: gs" occurs

### ISSUE THREAD

**Issue by chrissound** [imgproxy/imgproxy#331]
URL I'm using: http://localhost:8080/plain/gs://imgproxy-test-chris/2020-01-22-22:21:41

This file is public and exists in the bucket: https://storage.googleapis.com/imgproxy-test-chris/2020-01-22-22:21:41.jpeg

`verdaccio_1  | WARNING [2020-01-22T22:31:34Z] Completed in 102.529µs /plain/gs://imgproxy-test-chris/2020-01-22-22:21:41  request_id=8Ohq4zINGuIB36M4QNldsy method=GET status=404 error="Unknown processing option: gs"`

Seems I should not be getting this error? I've followed the instructions from: 
https://docs.imgproxy.net/#/serving_files_from_google_cloud_storage

I'm using the following docker environment:
```
version: '3.1'

services:
  verdaccio:
    image: darthsim/imgproxy:latest
    environment:
      - IMGPROXY_USE_GCS=true
      - 'IMGPROXY_GCS_KEY={...}'
    ports:
      - "8080:8080"
```
