### ISSUE TITLE
The imgproxy does not work through a proxy (socks5, https)

### ISSUE THREAD

**Issue by Claud** [imgproxy/imgproxy#370]
I tried to download pictures through a proxy, but this does not work.

Check through the "curl" ended with success. Proxy working normally.
```
curl -x socks5://45.91.9.60:18180 https://images.asos-media.com/products/weekday-grace-legeres-t-shirt/14423724-1-pinkdusty?$XXL$ --output img-test.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17741  100 17741    0     0   402k      0 --:--:-- --:--:-- --:--:--  402k
```

docker-compose.yml

```

version: "3"

services:
  imgproxy:
    image: darthsim/imgproxy:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "8080:8080"
    environment:
      IMGPROXY_DOWNLOAD_TIMEOUT: 5
      IMGPROXY_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
      HTTP_PROXY: "socks5://45.91.9.60:18180"
      HTTPS_PROXY: "socks5://45.91.9.60:18180"
      NO_PROXY: "localhost,127.0.0.0/8"
```

Result (I tried increasing the timeout to 30 seconds)

```
imgproxy_1  | WARNING [2020-04-01T17:33:34Z] Completed in 5.000335644s /insecure/auto/100/106/sm/0/aHR0cHM6Ly9pbWFnZXMuYXNvcy1tZWR/pYS5jb20vcHJvZHV/jdHMvd2Vla2Rhe/S1ncmFjZS1sZWdlcmVzLXQtc2hpcnQvMTQ0MjM3MjQtMS1waW5rZHVzdHk_JFhYTCQ.webp  request_id=0st9kg3cp-PIbJokv8htH method=GET status=404 error="Get \"https://images.asos-media.com/products/weekday-grace-legeres-t-shirt/14423724-1-pinkdusty?$XXL$\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

If I change the proxy to https

```
HTTP_PROXY: "https://45.91.9.60:8180"
HTTPS_PROXY: "https://45.91.9.60:8180"
```
Result
```
imgproxy_1  | WARNING [2020-04-01T17:31:28Z] Completed in 1.802326ms /insecure/auto/100/106/sm/0/aHR0cHM6Ly9pbWFnZXMuYXNvcy1tZWR/pYS5jb20vcHJvZHV/jdHMvd2Vla2Rhe/S1ncmFjZS1sZWdlcmVzLXQtc2hpcnQvMTQ0MjM3MjQtMS1waW5rZHVzdHk_JFhYTCQ.webp  request_id=aL3sD-fLWgZY0J8eJxBmx method=GET status=404 error="Get \"https://images.asos-media.com/products/weekday-grace-legeres-t-shirt/14423724-1-pinkdusty?$XXL$\": proxyconnect tcp: tls: first record does not look like a TLS handshake"

```

https://golang.org/pkg/net/http/

> // The proxy type is determined by the URL scheme. "http",
> // "https", and "socks5" are supported. If the scheme is empty,
> // "http" is assumed.

**Comment by DarthSim** [comment]
Sorry, I can't reproduce the issue. The following `docker-compose.yml` works fine for me:

```yml
version: "3"

services:
  imgproxy:
    image: darthsim/imgproxy:test
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      HTTP_PROXY: "socks5://proxy:1080"
      HTTPS_PROXY: "socks5://proxy:1080"
      NO_PROXY: "localhost,127.0.0.0/8"
  proxy:
    image: dijedodol/simple-socks5-server:latest
    restart: unless-stopped
    ports:
      - "1080:1080"
```

**Comment by DarthSim** [comment]
However, it doesn't work with your image https://images.asos-media.com/products/weekday-grace-legeres-t-shirt/14423724-1-pinkdusty. I guess there is some kind of protection in that server.

**Comment by DarthSim** [comment]
Ok, I got it. The server has a huge first-byte time. When I set an increased timeout, it works:

```yml
version: "3"

services:
  imgproxy:
    image: darthsim/imgproxy:test
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      IMGPROXY_DOWNLOAD_TIMEOUT: 30
      IMGPROXY_WRITE_TIMEOUT: 40
      HTTP_PROXY: "socks5://proxy:1080"
      HTTPS_PROXY: "socks5://proxy:1080"
      NO_PROXY: "localhost,127.0.0.0/8"
  proxy:
    image: dijedodol/simple-socks5-server:latest
    restart: unless-stopped
    ports:
      - "1080:1080"
```
