### ISSUE TITLE
Docker compose examples

### ISSUE THREAD

**Issue by cceyda** [imgproxy/imgproxy#620]
I'm searching for an image server and currently stuck deciding between thumbor & imgproxy.
Leaning towards imgproxy, because of advertised speed benefits.
But I like that thumbor has docker-compose ready examples that include nginx *caching*.

👍  I wish an example docker-compose recipe similar to https://github.com/MinimalCompact/thumbor was also available for imgproxy~
Other imgproxy caching alternatives are welcome too~

docker-compose examples really makes a difference on getting started with a project 🌟

**Comment by Tokenyet** [comment]
I could share my example for you, It's desgined for gcs, not sure what kind of example you want.

```
version: '3.2'
services:
  example_imgproxy:
      image: darthsim/imgproxy
      container_name: Example_Imgproxy # dns
      ports:
        - 39001:80 # host use 39001 to access the imgproxy
      environment:
        - IMGPROXY_BIND=80
        - IMGPROXY_USE_GCS=true
        - IMGPROXY_GCS_KEY=/auth/gcp-key.json
        - IMGPROXY_ALLOWED_SOURCES=gs://
      restart: on-failure
      volumes:
        - /hostpathyouwant/secrets/gcp-key.json:/auth/gcp-key.json
```
