### ISSUE TITLE
Not able to get imgproxy metrics in prometheus

### ISSUE THREAD

**Issue by Dhruv-Garg79** [imgproxy/imgproxy#628]
> INFO    [2021-05-05T09:25:18Z] Started /metrics  request_id=NyT6-fM108_otNvNKQt4_ method=GET
WARNING [2021-05-05T09:25:18Z] Completed in 279.011µs /metrics  request_id=NyT6-fM108_otNvNKQt4_ method=GET status=404 error="Invalid path: metrics"

I am getting above logs in docker logs imgproxy, if it helps

My prometheus.yml file
```
global:
  scrape_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9000']

  - job_name: 'img'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:5000']
```

cmd used to start imgproxy: 
> docker run -d --name img -e IMGPROXY_USE_S3=true -e IMGPROXY_BIND=:5000 -e IMGPROXY_PROMETHEUS_BIND=:9000 -e IMGPROXY_PROMETHEUS_NAMESPACE=img -p 5000:5000 -it darthsim/imgproxy
