### ISSUE TITLE
source URL in Plain not working

### ISSUE THREAD

**Issue by devudopw** [imgproxy/imgproxy#656]
Hello

I am testing source URL in Plain, but its not working.

request in base64, success:
`http://imgproxy.dev/unsafe/aHR0cHM6Ly92aWEucGxhY2Vob2/xkZXIuY29tLzE1MC5qcGc`

request in plain, fail:
`http://imgproxy.dev/unsafe/plain/https://via.placeholder.com/150.jpg`

logging:
`WARNING [2021-06-23T06:26:19Z] Completed in 1.335423ms /unsafe/plain/https:/via.placeholder.com/150.jpg  request_id=n60EpII1-bp9n2LO-GkNJ method=GET status=404 error="Get \"https:///via.placeholder.com/150.jpg\": http: no Host in request URL"`

docker-compose:
```
version: '3'

services:
  imgproxy:
    image: docker.io/darthsim/imgproxy:latest
    ports:
    - 80:8080/tcp
    restart: always
    environment:
      IMGPROXY_LOG_LEVEL: debug
```
