### ISSUE TITLE
IMGPROXY_USE_S3 and IMGPROXY_IGNORE_SSL_VERIFICATION are incompatible?

### ISSUE THREAD

**Issue by zhepa** [imgproxy/imgproxy#667]
Hi everyone, im trying to setup imgproxy in private network
We have Ceph S3 server with self-signed certificate and docs says that i can skip ssl verification with IMGPROXY_IGNORE_SSL_VERIFICATION flag, but it doesn't look like this

```
version: '3.7'

services:
  imgproxy:
  image: darthsim/imgproxy:v2
  environment:
    IMGPROXY_USE_S3: 'true'
    IMGPROXY_S3_REGION: 'default'
    IMGPROXY_S3_ENDPOINT: 'k8s-ceph-s3.example.com'
    AWS_ACCESS_KEY_ID: '...'
    AWS_SECRET_ACCESS_KEY: '...'
    IMGPROXY_KEY: 'bc21d3289a6b75a7e12d738aa5066be6'
    IMGPROXY_SALT: '18662e26839551bd8aa949a02277b51e'
    IMGPROXY_IGNORE_SSL_VERIFICATION: 'true'
  ports:
    - 8080:8080

```

with docker compose config above im still getting warning and generated url says 'Source image is unreachable'

```
imgproxy1_1  | WARNING [2021-07-08T15:20:08Z] Ignoring SSL verification is very unsafe
imgproxy1_1  | INFO    [2021-07-08T15:20:08Z] Starting server at :8080
imgproxy1_1  | INFO    [2021-07-08T15:20:40Z] Started /TPf3DB0c_ZJ7-i7MSO7IzmibWcPFy12o7vGrpIhaGEI/rs:fill:300:200:0/g:noea/dpr:2/czM6Ly9hdmF0YXJzLzM1MDAyMzM4LmpwZw  request_id=XzXyqafqQcNw4yGZWHUR7 method=GET
imgproxy1_1  | WARNING [2021-07-08T15:20:41Z] Completed in 1.1280455s /TPf3DB0c_ZJ7-i7MSO7IzmibWcPFy12o7vGrpIhaGEI/rs:fill:300:200:0/g:noea/dpr:2/czM6Ly9hdmF0YXJzLzM1MDAyMzM4LmpwZw  request_id=XzXyqafqQcNw4yGZWHUR7 method=GET status=404 error="Get \"s3://avatars/35002338.jpg\": RequestError: send request failed\ncaused by: Get \"https://k8s-ceph-s3.example.com/avatars/35002338.jpg\": x509: certificate signed by unknown authority"
```

is there any way to deal with it?
