### ISSUE TITLE
Can't make imageproxy work with shopware development docker => imageproxy docker

### ISSUE THREAD

**Issue by r4pt0s** [imgproxy/imgproxy#734]
Hi,

I try to make the following setup work to test imageproxy for our project:

- Shopware 6.4.6 via development template (./psh.phar docker:start)
- imageproxy:latest via docker-compose setup:

```
version: '3.2'

networks:
    default:
        external:
            name: shopware

services:
    imageproxy:
        image: darthsim/imgproxy:latest
        container_name: imageproxy # dns
        ports:
            - 7777:8080 # host use 7777 to access the imgproxy
        environment:
            - IMGPROXY_BASE_URL=http://localhost:8000/
```

Everything is up and running.
Imageproxy is working as expected by calling the [sample url](http://localhost:7777/insecure/rs:fill:300:400/g:sm/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk1tUTNabVk0/TnpZdFkyVm1ZaTAw/WkRSbUxUZ3lPREF0/WldZelpqaGxOemsx/TnpVMlhrRXlYa0Zx/Y0dkZVFYVnlOVGMz/TWpVek5USUAuanBn.jpg) form the docs.

But as soon as I try to access a image from the shopware container, I get the following error:

```imageproxy    | ERROR   [2021-11-15T16:19:42Z] Completed in 1.45595ms /insecure/plain/media/f1/1c/af/1636979981/paypal_100x100.jpg  request_id=Z_fAvHxvkxCc-KFG1IdJ5 method=GET status=500 error="Can't download source image: Get \"http://localhost:8000/media/f1/1c/af/1636979981/paypal_100x100.jpg\": dial tcp 127.0.0.1:8000: connect: connection refused"```

I'm not 100% sure where I did something wrong.
I can access every image from the web but not the ones which are available in the running shopware docker container.
