### ISSUE TITLE
Source image is unreachable when source image needs param

### ISSUE THREAD

**Issue by ronald** [imgproxy/imgproxy#766]
While trying to request an image which requires a key:
http://imgproxy/insecure/rs:fill:400:300/plain/https://example.com/path-to-img.jpg?k=1234567890

I get the response:
```
< HTTP/1.1 404 Not Found
< Server: nginx/1.18.0 (Ubuntu)
< Date: Fri, 07 Jan 2022 16:46:44 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 27
< Connection: keep-alive
< 
* Connection #0 to host imgproxy left intact
Source image is unreachable
```

I get the following log:
```
imgproxy_1  | INFO    [2022-01-07T16:31:17Z] Started /insecure/rs:fill:400:300/plain/https://example.com/path-to-img.jpg?k=1234567890&o=  request_id=6HrlAA-AvvBXporgIu-xJ method=GET
imgproxy_1  | WARNING [2022-01-07T16:31:17Z] Completed in 31.391506ms /insecure/rs:fill:400:300/plain/https://example.com/path-to-img.jpg?k=1234567890&o=  request_id=6HrlAA-AvvBXporgIu-xJ method=GET status=404 error="Can't download image; Status: 401; <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 401 Unauthorized</title>\n</head>\n<body><h2>HTTP ERROR 401 Unauthorized</h2>\n<table>\n<tr><th>URI:</th><td>/path-to-img.jpg</td></tr>\n<tr><th>STATUS:</th><td>401</td></tr>\n<tr><th>MESSAGE:</th><td>Unauthorized</td></tr>\n<tr><th>SERVLET:</th><td>jersey</td></tr>\n</table>\n\n</body>\n</html>\n"
```

docker-compose:
```
version: '3.1'
services:
  imgproxy:
    image: darthsim/imgproxy:v3.1
    restart: always
    environment:
      # https://github.com/imgproxy/imgproxy/blob/master/docs/configuration.md
      IMGPROXY_ALLOWED_SOURCES: https://example.com/
      IMGPROXY_ENABLE_CLIENT_HINTS: 1
    ports:
     - "8080:8080"
```

Direct access to `https://example.com/path-to-img.jpg?k=1234567890` works fine.

Can you please help me?
