### ISSUE TITLE
Datadog integration doesn't seem to be working: EKS and helm chart

### ISSUE THREAD

**Issue by jslusher** [imgproxy/imgproxy#770]
I have an installation of imgproxy using the helm chart (via kustomize) on an EKS cluster. Following the [docs](https://docs.imgproxy.net/datadog), I have the chart values set to this:

```
      datadog:
        enabled: true
        env: test
        metricsEnabled: true
        tags: "cluster:test-cluster"
        traceDebug: true
```

I also used a kustomize [patchesStrategicMerge](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing) to set `DD_AGENT_HOST` to the [appropriate](https://docs.datadoghq.com/agent/kubernetes/apm/?tab=ipport#configure-your-application-pods-in-order-to-communicate-with-the-datadog-agent) `status.hostIP` value for kubernetes pods:

```
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

The datadog env variables look like this in the pod:

```
kubectl exec -it imgproxy-xxxxxxxxxx -- env | grep DD_
DD_AGENT_HOST=172.25.4.139
DD_TAGS=cluster:test-cluster
DD_ENV=test
DD_TRACE_DEBUG=true
DD_TRACE_AGENT_PORT=8126
DD_DOGSTATSD_PORT=8125
DD_SERVICE=imgproxy
DD_RUNTIME_METRICS_ENABLED=true
```

I've verified our datadog agent is running and listening on the default ports and should be receiving traces and metrics, but I can't seem to find the ones mentioned in the docs anywhere in datadog:

I tried searching in metrics explorer for "service:imgproxy" and metrics under the namespace "imgproxy", but it comes up empty. When I search for the tag "service:imgproxy" in the metrics summary, I see some metrics under the `datadog` namespace (`datadog.dogstatsd` and `datadog.trace` mostly) and then some metrics under the `runtime.go` namespace (`runtime.go.mem_stats` mostly). In the docs it mentions some response time and processing metrics and I can't seem to find them. Should they be under a `imgproxy` namespace? The docs are not clear on the naming of these metrics and I haven't had any luck finding them.

Also, as you see I have `DD_TRACE_DEBUG` set to true, but I don't see any debug logs in my pod's log output. Should I be looking for those debug logs somewhere else?
