### ISSUE TITLE
Source image is unreachable

### ISSUE THREAD

**Issue by UserFengFeng** [imgproxy/imgproxy#857]
I tried to access the MINIO image path through imgproxy, and this problem appeared

ubuntu18.04
minio port: 6090
imgproxy  port: 8080
minio img url path : [http://10.0.0.174:6090/test1/xxx.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=95QP6GGLJ54PHPGCFJWJ%2F20220425%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220425T053524Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5NVFQNkdHTEo1NFBIUEdDRkpXSiIsImV4cCI6MTY1MDg2NzU4NSwicGFyZW50IjoiYWRtaW4ifQ.J-zChUGFx4wF7RmEYoBhgVJ3vXPIx5FAltvnKPNEaMBx_-qIDhB64zr4d6HqrPaJs_2UCwXq8sXMPP5AaM-2XA&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=6e03e37e3ea86fdb0acb9aa52f27b0ee5a1c80da4bec75a72a80f48bdb38a74f](url)

docker-compose.yml  config file

version: '3.1' 
services:  
  minio:  
    image: minio/minio  
    restart: always  
    environment: 
      MINIO_ACCESS_KEY: admin  
      MINIO_SECRET_KEY: admin123  
      MINIO_REGION: us-east-1  
    ports:  
      - "8081:6090"  
    volumes:  
      - "./minio/storage:/data"  
    command: server /data  
  imgproxy:  
    image: darthsim/imgproxy  
    restart: always  
    environment:  
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /data # you can link to minio volume to imgproxy and use as a local filesystem.  
      IMGPROXY_USE_S3: 'true'  
      IMGPROXY_S3_ENDPOINT: http://10.0.0.174:6090  
      AWS_ACCESS_KEY_ID: admin  
      AWS_SECRET_ACCESS_KEY: admin123  
      AWS_REGION: us-east-1  
    ports:  
      - "8082:8080"  
    links:  
      - minio # it doesn't matter actually by default all containers can reach each other with their service name.  
    volumes:  
      - "./minio/storage:/data" # link to minio volume to imgproxy's /opt folder for local filesystem.  

Final visit path
[http://10.0.0.174:8082/resize:fill:1000:1000:0/plain/http://10.0.0.174:6090/test1/xxx.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=95QP6GGLJ54PHPGCFJWJ%252F20220425%252Fus-east-1%252Fs3%252Faws4_request&X-Amz-Date=20220425T051958Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI5NVFQNkdHTEo1NFBIUEdDRkpXSiIsImV4cCI6MTY1MDg2NzU4NSwicGFyZW50IjoiYWRtaW4ifQ.J-zChUGFx4wF7RmEYoBhgVJ3vXPIx5FAltvnKPNEaMBx_-qIDhB64zr4d6HqrPaJs_2UCwXq8sXMPP5AaM-2XA&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=76773fb8ce096f96e15dd412ed6e9f44085f030102b944d330539c014573acb1](url)
![image](https://user-images.githubusercontent.com/43665350/165201133-4e4ff12f-93a5-4835-9f8a-a42698047d4b.png)

**Comment by wwwdepot** [comment]
Minio container listens on port 9000 by default. 

docker-compose file

```yml
version: '3.7'
services:
  minio1:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "43003:9000"
      - "43004:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: miniorofl
      MINIO_SITE_REGION: us-east-1
    volumes:
      - ./data:/data
  imgproxy1:
    image: darthsim/imgproxy
    environment:
      IMGPROXY_USE_S3: 'true'
      IMGPROXY_S3_ENDPOINT: "http://minio1:9000"
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: miniorofl
      AWS_REGION: us-east-1
    ports:
      - "43005:8080"
```

Create a bucket `website` & upload any image.

Open imgproxy in browser
```
http://localhost:43005/unsafe/w:500/plain/s3://website/blah.jpg
```
